### PR TITLE
Update to pt_PT translation

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by mansj** [comment]
Looking at this, I'm trying to understand what improvements were made. Can you clarify, @pedro-mendonca ?

**Comment by pedro-mendonca** [comment]
Hi @mansj 
Of course, most of the changes these where in the word chosen to translate the word _media_ according to the translation guidelines of portuguese translation team.

But please wait, I'll include some changes to comply with the latest changes on commit https://github.com/mansj/enable-media-replace/commit/0a346088e5dcf2b1611a61691b46f9d68f0bd196 that concatenates some strings to include placeholders.

**Comment by pedro-mendonca** [comment]
@mansj 
I've just updated the PR with the latest changes in concatenated strings, it's ready now.

**Comment by tyrann0us** [comment]
Why not use [GlotPress](https://translate.wordpress.org/locale/pl/default/wp-plugins/enable-media-replace) for this?
Using GlotPress would have made v3.0.6 superfluous (since changing `Tested up to` does _not_ requires to release a new version).

**Comment by pedro-mendonca** [comment]
@tyrann0us I'm also using GlotPress, but currently only _Development_ translation is available, this is the only way to get the plugin translated for most users.

**Pull request merged**
