### PR TITLE
Update to .po/.mo files ENG and PT (3.0.2)

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Added two more strings to both original ENG file and PT already updated
and translated to last 3.0.2 version.

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
Hi
Have you notested these file changes?
I'm just asking because you've close this without any comment and I would like to understand if you really like or not this kind of help on translation strings related problems.
Thanks.
Pedro.

**Comment by mansj** [comment]
Oh, I'm sorry, I totally misunderstood your request. I'll reopen this and add them on the next release.

**Comment by pedro-mendonca** [comment]
I'm keeping portuguese files up to date, so I've sweeped the code with Poedit and found two adicional strings. For that, I've found they lack text-domain 'enable-media-replace' and I've suggested to add it. One of them is really included in main WordPress lang files, but I believe that if it appears in Poedit nobody will verify that and just translate everything to 100%.
So I've updated PT and EN po/mo files because I believe the EN is the base that most other translators will use. I you want I'll just check on the PT one in the future.

**Comment by mansj** [comment]
No that's good, keep up the English as well if you would! Thank you.

**Pull request merged**
